
CREATE DATABASE PIZZAHUTT

SELECT * FROM ORDER_DETAILS
SELECT * FROM ORDERS
SELECT * FROM PIZZA_TYPES
SELECT * FROM PIZZAS

--BASIC:-
--(1)RETRIEVE THE TOTAL NUMBER OF ORDERS PLACED.
SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS FROM ORDERS

--(2)CALCULATE THE TOTAL REVENUE GENERATED FROM PIZZA SALES.
SELECT 
ROUND(SUM(OD.QUANTITY * PZ.PRICE),2) AS TOTAL_SALES 
FROM ORDER_DETAILS OD
JOIN PIZZAS PZ
ON PZ.PIZZA_ID = OD.PIZZA_ID

--(3)IDENTIFY THE HIGHEST-PRICED PIZZA.
SELECT TOP 1
PT.NAME,ROUND(PZ.PRICE,2)
FROM PIZZA_TYPES PT
JOIN PIZZAS PZ
ON PT.PIZZA_TYPE_ID = PZ.PIZZA_TYPE_ID
ORDER BY PZ.PRICE DESC

--(4)IDENTIFY THE MOST COMMON PIZZA SIZE ORDERED.
SELECT PZ.SIZE, COUNT(OD.ORDER_DETAILS_ID) AS ORDER_COUNT
FROM PIZZAS PZ
JOIN ORDER_DETAILS OD
ON PZ.PIZZA_ID = OD.PIZZA_ID
GROUP BY PZ.SIZE

--(5)LIST THE TOP 5 MOST ORDERED PIZZA TYPES ALONG WITH THEIR QUANTITIES.

SELECT TOP 5
PT.NAME,
SUM(OD.QUANTITY) AS TOTAL_QUANTITY
FROM PIZZA_TYPES PT
JOIN PIZZAS PZ
ON PT.PIZZA_TYPE_ID = PZ.PIZZA_TYPE_ID
JOIN ORDER_DETAILS OD
ON OD.PIZZA_ID = PZ.PIZZA_ID
GROUP BY PT.NAME
ORDER BY TOTAL_QUANTITY DESC


--INTERMEDIATE:
--(6)JOIN THE NECESSARY TABLES TO FIND THE TOTAL QUANTITY OF EACH PIZZA CATEGORY ORDERED.
SELECT 
PT.CATEGORY,
SUM(OD.QUANTITY) AS TOTAL_QUANTITY
FROM PIZZA_TYPES PT
JOIN PIZZAS PZ
ON PT.PIZZA_TYPE_ID = PZ.PIZZA_TYPE_ID
JOIN ORDER_DETAILS OD
ON OD.PIZZA_ID = PZ.PIZZA_ID
GROUP BY PT.CATEGORY
ORDER BY TOTAL_QUANTITY DESC

--(7)DETERMINE THE DISTRIBUTION OF ORDERS BY HOUR OF THE DAY.

SELECT DATEPART(HOUR, TIME) AS ORDER_HOURS,
COUNT(ORDER_ID) AS ORDER_COUNT
FROM ORDERS
GROUP BY DATEPART(HOUR, TIME)
ORDER BY ORDER_HOURS DESC

--(8)JOIN RELEVANT TABLES TO FIND THE CATEGORY-WISE DISTRIBUTION OF PIZZAS.

SELECT CATEGORY,
COUNT(NAME) AS NAME_COUNT
FROM PIZZA_TYPES
GROUP BY CATEGORY

--(9)GROUP THE ORDERS BY DATE AND CALCULATE THE AVERAGE NUMBER OF PIZZAS ORDERED PER DAY.

SELECT AVG(ORDER_QUANTITY) AS AVG_COUNT
FROM 
(SELECT O.DATE,
SUM(OD.QUANTITY) AS ORDER_QUANTITY
FROM ORDERS O
JOIN ORDER_DETAILS OD
ON O.ORDER_ID = OD.ORDER_ID
GROUP BY O.DATE) A

--(10)DETERMINE THE TOP 3 MOST ORDERED PIZZA TYPES BASED ON REVENUE.

SELECT TOP 3
PT.NAME,
SUM(OD.QUANTITY * PZ.PRICE) AS REVENUE
FROM PIZZA_TYPES PT
JOIN PIZZAS PZ
ON PT.PIZZA_TYPE_ID = PZ.PIZZA_TYPE_ID
JOIN ORDER_DETAILS OD
ON OD.PIZZA_ID = PZ.PIZZA_ID
GROUP BY PT.NAME
ORDER BY REVENUE DESC

--ADVANCED:
--(11)CALCULATE THE PERCENTAGE CONTRIBUTION OF EACH PIZZA TYPE TO TOTAL REVENUE.
SELECT 
PT.CATEGORY,
SUM(OD.QUANTITY * PZ.PRICE) AS REVENUE
FROM PIZZA_TYPES PT
JOIN PIZZAS PZ
ON PT.PIZZA_TYPE_ID = PZ.PIZZA_TYPE_ID
JOIN ORDER_DETAILS OD
ON OD.PIZZA_ID = PZ.PIZZA_ID
GROUP BY PT.CATEGORY
ORDER BY REVENUE DESC

--(12)ANALYZE THE CUMULATIVE REVENUE GENERATED OVER TIME.
SELECT DATE,
SUM(REVENUE) OVER ( ORDER BY DATE) AS CUMM_REVENUE
FROM
(SELECT 
O.DATE,
SUM(OD.QUANTITY * PZ.PRICE) AS REVENUE
FROM ORDER_DETAILS OD 
JOIN PIZZAS PZ
ON OD.PIZZA_ID = PZ.PIZZA_ID
JOIN ORDERS O
ON OD.ORDER_ID = O.ORDER_ID
GROUP BY O.DATE ) AS SALES

--(13)DETERMINE THE TOP 3 MOST ORDERED PIZZA TYPES BASED ON REVENUE FOR EACH PIZZA CATEGORY.
SELECT NAME,REVENUE
FROM
(SELECT CATEGORY,NAME,REVENUE,
RANK() OVER (  PARTITION BY CATEGORY ORDER BY REVENUE DESC) AS RN 
FROM 
(SELECT PT.category,
PT.NAME,
SUM(OD.QUANTITY * PZ.PRICE) AS REVENUE
FROM PIZZA_TYPES PT
JOIN PIZZAS PZ
ON PT.PIZZA_TYPE_ID = PZ.PIZZA_TYPE_ID
JOIN ORDER_DETAILS OD
ON OD.PIZZA_ID = PZ.PIZZA_ID
GROUP BY PT.CATEGORY,
PT.NAME) AS A) B 
WHERE RN<= 3
